# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build: # test with circleci/golang:1.9
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/filipecosta90/hdrhistogram
    steps:
      - checkout
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

workflows:
  version: 2
  commit:
    jobs:
      - build
